### ISSUE TITLE
Azure TFLXTLS notebook does not work

### ISSUE THREAD

**Issue by fromeijn** [MicrochipTech/cryptoauth_trustplatform_designsuite#1]
```
def execute_azure_login(b):
    Azure_login.button_style = azure_account_login()
    
Azure_login = widgets.Button(description = "Azure login")
Azure_login.on_click(execute_azure_login)
```
does absolutely nothing

also whats up with TFLXTLS_azure_connect.ipynb & TLFXTLS_azure_connect.ipynb?

I think it has something to do with widgets that are not working, tried the same with some AWS notebooks

**Comment by adithyayuri** [comment]
`Azure_login = widgets.Button(description = "Azure login")`
is supposed to create a button which directs to Azure login page.

We have seen this issue before when installing ipywidgets python module for the very first time. This seems to be a issue with ipywidgets. This is usually resolved if you reopen the notebook. If you still face the issue I would recommend contacting [Microchip Support](https://microchipsupport.force.com/).

Regarding files TFLXTLS_azure_connect.ipynb & TLFXTLS_azure_connect.ipynb:
1. TFLXTLS_azure_connect.ipynb is the correct notebook for Azure example.
2. TLFXTLS_azure_connect.ipynb is a older duplicate version and will be deleted in the next release. Thanks for catching this.
