### ISSUE TITLE
Trust and GO AWS Connection Issue

### ISSUE THREAD

**Issue by bubshowlett** [MicrochipTech/cryptoauth_trustplatform_designsuite#2]
I'm unable to use the trust and go AWS connect project. 
The project builds and programs correctly, however the only output in the terminal is the following,

Device Serial Number : xxxxxxxxxxxxxx
Config Zone: Locked
Data Zone: Locked
(APP)(INFO)Chip ID 1503a0

I using the Wifi 7 Click Board as the wifi module that contains a WINC1510 also.

**Comment by SPGTools** [comment]
Please update WINC firmware using the bat file in assets/winc_firmware_upgrade.

If you continue to have the problem, raise a support ticket. Please refer to instructions here, https://microchipsupport.force.com/s/article/How-to-submit-a-case

**Comment by KalyanCManukonda** [comment]
Please update WINC firmware using the bat file in assets/winc_firmware_upgrade.

If you continue to have the problem, raise a support ticket. Please refer to instructions here, https://microchipsupport.force.com/s/article/How-to-submit-a-case
